name: 'Get Current Build Count'
description: 'Get the current build count for a given pipeline ID'
inputs:
  pipeline-id: 
    description: 'The build definition ID to get the current build count for'
    required: true
  ado-token: 
    description: 'The Azure DevOps PAT token'
    required: true
  ado-url: 
    description: 'The Azure DevOps URL'
    required: true
outputs:
  current-build-count:
    description: 'The current build count for the specified pipeline'
    value: ${{ steps.get-current-build-count.outputs.CURRENT_BUILD_COUNT }}

runs:
  using: "composite"
  steps:
    - name: Get current build count
      id: get-current-build-count
      shell: bash
      run: |
        echo "Getting current build count for pipeline ID ${{ inputs.pipeline-id }}"
        CURRENT_BUILD_COUNT=$(curl -s -H "Authorization: Basic $(echo -n ":${{ inputs.ado-token }}}" | base64 -w0)" \
          "${{ inputs.ado-url }}/_apis/build/builds?api-version=6.0&definitions=${{ inputs.pipeline-id }}&queryOrder=queueTimeDescending&\$top=1" | \
          jq '.value[0].id')
        echo "CURRENT_BUILD_COUNT=$CURRENT_BUILD_COUNT" >> $GITHUB_ENV
        echo "Current build count: $CURRENT_BUILD_COUNT"
