name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  basic:
    name: Test Basic Pipeline Execution with No Parameters
    runs-on: ubuntu-latest

    env:
      pipeline-name: 'it-basic'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: tjcorr/pipelines@node20
        with: 
          azure-devops-project-url: ${{ vars.ADO_URL }}
          azure-pipeline-name: ${{ env.pipeline-name }}
          azure-devops-token: ${{ secrets.ADO_TOKEN }}
          
      - name: Verify new pipeline execution
        uses: ./.github/actions/verify-execution
        with:
          ado-token: ${{ secrets.ADO_TOKEN }}
          ado-url: ${{ vars.ADO_URL }}
          pipeline-name: ${{ env.pipeline-name }}
          build-url: ${{ steps.tjcorr-pipelines.outputs.pipeline-url }}

  basic-with-variables:
    name: Test Basic Pipeline Execution with Variables
    runs-on: ubuntu-latest

    env:
      pipeline-name: 'it-basic-var'
      variables: '{ "testVar1": "testValue1", "testVar2": "testValue2" }'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: tjcorr/pipelines@node20
        with: 
          azure-devops-project-url: ${{ vars.ADO_URL }}
          azure-pipeline-name: ${{ env.pipeline-name }}
          azure-devops-token: ${{ secrets.ADO_TOKEN }}
          azure-pipeline-variables: ${{ env.variables }}

      - name: Verify new pipeline execution
        uses: ./.github/actions/verify-execution
        with:
          ado-token: ${{ secrets.ADO_TOKEN }}
          ado-url: ${{ vars.ADO_URL }}
          pipeline-name: ${{ env.pipeline-name }}
          build-url: ${{ steps.tjcorr-pipelines.outputs.pipeline-url }}
          variables: ${{ env.variables }}
  