name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  basic:
    name: Test Basic Pipeline Execution with No Parameters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get build definition ID
        id: get-build-definition-id
        uses: ./.github/actions/get-build-definition-id
        with:
          pipeline-name: 'it-basic'
          ado-token: ${{ secrets.ADO_TOKEN }}
          ado-url: ${{ vars.ADO_URL }}

      - name: Get current build count
        id: get-current-build-count
        uses: ./.github/actions/get-build-definition-id
        with:
          pipeline-id: ${{ steps.get-build-definition-id.outputs.PIPELINE_ID }}
          ado-token: ${{ secrets.ADO_TOKEN }}
          ado-url: ${{ vars.ADO_URL }}

      - uses: tjcorr/pipelines@node20
        with: 
          azure-devops-project-url: ${{ vars.ADO_URL }}
          azure-pipeline-name: 'it-basic'
          azure-devops-token: ${{ secrets.ADO_TOKEN }}
          
      - name: Verify new pipeline execution
        uses: ./.github/actions/verify-execution
        with:
          pipeline-id: ${{ steps.get-build-definition-id.outputs.PIPELINE_ID }}
          ado-token: ${{ secrets.ADO_TOKEN }}
          ado-url: ${{ vars.ADO_URL }}
          old-build-count: ${{ steps.get-current-build-count.outputs.CURRENT_BUILD_COUNT }}
