name: Integration Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: tjcorr/pipelines@node20
        with: 
          azure-devops-project-url: ${{ vars.ADO_URL }}
          azure-pipeline-name: 'it-basic'
          azure-devops-token: ${{ secrets.ADO_TOKEN }}
